if(NOT DEFINED DEPTHGEN_PACKAGE_ROOT OR NOT DEFINED DEPTHGEN_PACKAGE_NAME)
  message(FATAL_ERROR "ZIP creation requires DEPTHGEN_PACKAGE_ROOT and DEPTHGEN_PACKAGE_NAME.")
endif()
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E tar cf "${DEPTHGEN_PACKAGE_NAME}" --format=zip .
  WORKING_DIRECTORY "${DEPTHGEN_PACKAGE_ROOT}"
  RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Could not create ${DEPTHGEN_PACKAGE_NAME}.")
endif()
